//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieRekrutacyjne.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserPermission
    {
        public int UserPermissionID { get; set; }

        [Display(Name = "Login u¿ytkownika")]
        public Nullable<int> UserID { get; set; }
        [Display(Name = "Kod uprawnienia")]
        public Nullable<int> PermissionID { get; set; }
    
        public virtual Permissions Permissions { get; set; }
        public virtual Users Users { get; set; }
    }
}
