//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieRekrutacyjne.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Security.Cryptography;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.UserPermission = new HashSet<UserPermission>();
        }

        [Display(Name = "Login")]
        public int UserId { get; set; }

        [Display(Name = "Login")]
        [Required(ErrorMessage = "Podaj login")]
        [Remote("DoesLoginExist", "Users", HttpMethod = "POST", ErrorMessage = "Podany login ju¿ istnieje")]
        public string Login { get; set; }

        [Display(Name = "Has³o")]
        [Required(ErrorMessage = "Podaj has³o")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        
        [Display(Name = "Imiê")]
        [Required(ErrorMessage = "Podaj imiê")]
        public string FirstName { get; set; }

        [Display(Name = "Nazwisko")]
        [Required(ErrorMessage = "Podaj nazwisko")]
        public string LastName { get; set; }

        [Display(Name = "PESEL")]
        [Required(ErrorMessage = "Podaj PESEL")]
        [Remote("DoesPeselExist", "Users", HttpMethod = "POST", ErrorMessage = "Podany PESEL ju¿ istnieje")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "PESEL powinien sk³adaæ siê z 11 cyfr")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "PESEL powinien sk³adaæ siê wy³¹cznie z cyfr")]
        public string PESEL { get; set; }

        [Display(Name = "Data urodzenia")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }

        [Display(Name = "Miejsce urodzenia")]
        public string PlaceOfBirth { get; set; }

        [Display(Name = "Stanowisko pracy")]
        public string Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPermission> UserPermission { get; set; }

        public virtual Permissions Permissions { get; set; }
    }
}
